name: Build ROCK

on:
  workflow_call:

jobs:
  build:
    name: Build ROCK
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - id: rockcraft
        name: Build ROCK
        uses: canonical/craft-actions/rockcraft-pack@main
      
      - name: Upload ROCK artifact
        uses: actions/upload-artifact@v3
        with:
            name: ratings-rock
            path: ${{ steps.rockcraft.outputs.rock }}
