name: Build/Test Charm

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: |
          cd operator
          tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: |
          cd operator
          tox -e unit

  integration-test:
    name: Integration tests (microk8s)
    runs-on: ubuntu-22.04
    needs:
      - lint
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Do some preemptive setup for the ingress integration test so that our
      # bogus dns name resolves properly.
      - name: Setup hosts for tests
        run: |
          echo "10.64.140.43 testing-ratings.foo.bar" | sudo tee -a /etc/hosts
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.27-strict/stable
          juju-channel: 3.2/stable
          microk8s-group: snap_microk8s
          microk8s-addons: "hostpath-storage dns metallb:10.64.140.43-10.64.140.43"
      - name: Run integration tests
        run: |
          cd operator
          tox -e integration -- --model=testing
