name: Push (main)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  build-rock:
    uses: ./.github/workflows/build-rock.yaml

  publish-rock:
    name: Publish ROCK to GHCR
    runs-on: ubuntu-latest
    needs:
      - build-rock
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch ROCK artifact
        uses: actions/download-artifact@v3
        with:
          name: ratings-rock

      - name: Upload ROCK to ghcr.io
        run: |
          commit="$(git rev-parse --short HEAD)"

          # Upload ROCK to ghcr.io/tim-hm/ratings:main-<commit>
          sudo skopeo --insecure-policy copy \
            "oci-archive:$(realpath ./ratings_*.rock)" \
            "docker://ghcr.io/tim-hm/ratings:main-${commit}" \
            --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"

          # Upload ROCK to ghcr.io/tim-hm/ratings:latest
          sudo skopeo --insecure-policy copy \
            "oci-archive:$(realpath ./ratings_*.rock)" \
            "docker://ghcr.io/tim-hm/ratings:latest" \
            --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"
